### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by gaborluk** [rangle/redux-segment#28]
Hey guys,

I'm getting this error when I `import { createTracker } from 'redux-segment'`:

`Module not found: Error: Cannot resolve module 'redux-segment' in D:\...`

The module has installed successfully, and is present in `node_modules`. I've looked at `package.json`, and it lists a certain `redux-segment.js` as its entry point, but that file doesn't seem to exist within the module. Could you please give me some guidance on this?

Thanks in advance.

**Comment by gaborluk** [comment]
Just some additional information: I can't actually `npm install redux-segment` because I receive the error below:
```
$ npm install redux-segment
npm ERR! tar.unpack untar error C:\Users\...\AppData\Roaming\npm-cache\redux-segment\0.7.2\package.tgz
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "redux-segment"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! path D:\...\node_modules\.staging\redux-segment-be385db1\Icon
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

'pm ERR! enoent ENOENT: no such file or directory, open 'D:\...\node_modules\.staging\redux-segment-be385db1\Icon
'pm ERR! enoent ENOENT: no such file or directory, open 'D:\...\node_modules\.staging\redux-segment-be385db1\Icon
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```
_(Paths edited for privacy.)_

Of course, `npm install` for this project also fails because of this, so I install `redux-segment` manually with `npm install https://github.com/rangle/redux-segment.git`, which works fine. Not sure if this is related, but I felt like adding it. I'm on a Windows 7 x64 machine, for what it's worth.

**Comment by bertrandk** [comment]
Thanks for the additional info. I'm looking into it and will make sure a fix ships with (at least) v1.0.

**Comment by gaborluk** [comment]
Much appreciated, @bertrandk. Let me know if you need any more information from me.

For everyone else having this issue: a temporary workaround is getting your hands on a copy of the `node_modules/redux-segment` folder from an installation on a Unix machine, and putting that in your `node_modules`.

**Comment by DerekStrickland** [comment]
+1 fix needed.  Thanks @gaborluk for the workaround.

**Comment by bertrandk** [comment]
It's been a little busy but this fix is still coming. FWIW, you can get a copy here as a (non-ideal) workaround for now: https://npmcdn.com/redux-segment@0.7.2

**Comment by alecperkey** [comment]
workaround worked for me: npm install --save https://github.com/rangle/redux-segment/tarball/master 

this seems to happen on windows 7 when using npm v3+

https://github.com/mithunsatheesh/node-rules/issues/32
https://github.com/npm/npm/issues/10455

**Comment by benigeri** [comment]
so I get notified

**Comment by morenoh149** [comment]
https://help.github.com/articles/subscribing-to-conversations/

**Comment by chollier** [comment]
I think you had an issue while releasing `1.0.0`, there is not `dist/` folder in there

**Comment by chollier** [comment]
@bertrandk Probably because you have `dist` in your `.gitignore` and no specific `.npmignore`, in this case npm publish uses `.gitignore`

**Comment by chollier** [comment]
Solved by df96b10c5bb91e19a89e552f2c8e08c835112d89

**Comment by Kolyasya** [comment]
Still have this issue on Windows with 1.3.0 version
`
D:\Server\domains\wood>npm install --save redux-segment
npm ERR! tar.unpack untar error C:\Users\Nikolay\AppData\Roaming\npm-cache\redux
-segment\1.3.0\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "redux-segment"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path D:\Server\domains\wood\node_modules\redux-segment\Icon
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\Server\domains\wood\node_modules\redux-segment\Icon
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Server\domains\wood\npm-debug.log
`

**Comment by Kolyasya** [comment]
I've tried complitely reinstall node.js and meteor app, also reinstalled git and 7-zip (to fix tar problems with meteor).
Still have no success. Using Windows 7 x64

**Comment by Kolyasya** [comment]
@bertrandk hello, do you have any updates on this?
Seems it should have simple fix, but can't continue development on the Windows because of this problem.
If you need any details from me about the bug, I can provide.

**Comment by bertrandk** [comment]
Sorry for the wait @Kolyasya. I know what the problem is...just not sure why it's happening yet.

The Icon file it's tripping over is `.gitignore`'d but `npm publish` is failing to pick up that rule. As a result, `npm install`-ing a build from github should work just fine but installing from npm is currently failing on Windows.

I should have a fix soon.

**Comment by bertrandk** [comment]
@Kolyasya Try v1.4.1 and let me know. Seems to work fine on my Windows machine.

**Comment by Kolyasya** [comment]
@bertrandk seems to be ok now! thank you :-)
